### ISSUE TITLE
Adding it to the migrations plugin

### ISSUE THREAD

**Issue by dereuromark** [vierge-noire/cakephp-test-migrator#1]
Do you have plans to make this part of the migrations plugin directly?
This would probably help especially plugins a lot to verify their migrations.

They already have a require-dev usually on Migrations
So having an easy to use test harness then would be super useful I would imagine.

**Comment by pabloelcolombiano** [comment]
That is a very good idea!
I'll give it a try asap.

**Comment by dereuromark** [comment]
For example in https://github.com/dereuromark/cakephp-queue/tree/master/config/Migrations
I got quite a few migrations

And the Migrations plugin is already a dependency for testing.
So I could then do a MigrationsTest inside my plugin test suite which then just executes those on a dummy DB and checks if that worked :)

**Comment by pabloelcolombiano** [comment]
In your case, I would take this approach:
1. Getting rid of your two Fixtures, QueueProcessesFixture.php and QueuedJobsFixture.php
2. Create your test data on the fly. This seems to be mostly the case already, meaning your fixtures are more a schema emulator than seeding.
3. Now that you are freed from Fixtures, use the listener given here: https://github.com/vierge-noire/cakephp-test-suite-light
This will not drop tables at any time, only truncate the dirty ones, so you can...
4. Run the Migrator in tests/bootstrap.php 

Steps 1 and 2 are optional.
Step 3 is necessary for step 4.
Step 4 will test your migrations indirectly in the deepest manner possible: all your DB-dependent tests rely on it. Bad migrations should trigger errors somewhere in your tests.

This is more the idea behind the Migrator, and might be useful to your app.

This said, I confirm that the Migrator fits in the Migrations Plugin.

**Comment by pabloelcolombiano** [comment]
I could propose a pull request in the CakePHP Queue plugin, instead of giving 2 cents advices. Is this something you think should be given a try?

**Comment by dereuromark** [comment]
Oh maybe I understand this plugin wrong
This is not for testing migrations?

**Comment by pabloelcolombiano** [comment]
No, this is not for testing migrations.

But it can be used in order to test Migrations, yes. The Migration Plugin already has everything at hand to run Migrations on the fly. In your test you can do:

```
$migrations = new Migrations();
$migrations->migrate($yourMigrationConfig);

// Assert whatever
```
No need really to have a package extra for that. 

The Migrator is rather meant for developers using the CakePHP Fixture Factories and/or the CakePHP Test Suite Light, in order to have migrations run prior to the tests. Therefore, it is called once in tests/bootstrap.php.

 This has the following advantages:
1. your migrations get involved in your test workflow, without having to write tests for them. Yes your migrations get tested as a positive side effect.

2. your tests run faster (no dropping of tables)

3. you maintain your DB schema at one place only, namely in the migrations and not in the fixtures additionaly.

4. if you switch branches, the Migrator will detect if a migration is up and missing, meaning you have a schema inconsistency. For example, you've moved from a branch featuring a migration back to master. The Migrator will detect that, drop your test DB and run the migrations freshly again. Big warm up. Back to the feature branch, it will run only the missing migration, as expected. Small warm up. The rest of the time, no warm up.

Does this make sense?

**Comment by dereuromark** [comment]
Yes, thank you.
But then it wasnt quite what I had in mind for my plugins at this time it seems.

Anyway, thank you and feel free to make any PR for Migrations plugin you seem useful.
